set -g prefix ^B

bind-key v display-popup -w 60% -h 70% -E -d . -S $SHELL
bind-key H display-popup -w 50% -h 60% -E "htop"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux'

# Configure the catppuccin plugin
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,( ),}"

set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"
set -g base-index 1 
set -g status-position top
set -g history-limit 10000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
setw -g mode-keys vi

bind-key -n M-Left send-keys M-b
bind-key -n M-Right send-keys M-f

bind -n M-n new-window
bind -n M-b kill-pane
bind -n M-l next-window
bind -n M-h previous-window

# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Down select-pane -D
bind -n M-Up select-pane -U

bind-key l select-pane -R
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U

bind-key u last-window

bind-key | split-window -h
bind-key - split-window -v

# set -g @catppuccin_status_modules "application session cpu uptime"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 50
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"         # TODO: fix cpu status
set -ag status-right "#{E:@catppuccin_status_application}"
# set -ag status-right "#[fg=cyan] %I:%M"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_battery}"

run '~/.tmux/plugins/tpm/tpm'
