
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
exec-once = nm-applet --indicator &
# exec-once = waybar & hyprpaper & firefox
exec-once = hypridle &
# exec-once = swww-daemon & /home/ameen/Pictures/wallpapers/wallpaper.sh 
exec-once = swww-daemon &
exec-once = mpd &
exec-once = waybar & 
exec-once=/usr/lib/pam_kwallet_init &
exec-once = swaync &
# exec-once=systemctl --user enable mpd.service && systemctl --user start  mpd.service
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets &
# exec-once = hyprctl setcursor 'Bibata-Modern-Classic' 21
# exec-once = ibus-daemon -drx
exec-once = /home/ameen/.limiter/new_timer.sh
# exec-once = eww daemon
# exec-once = elephant
# exec-once = walker --gapplication-service

#for libadwaita gtk4 apps you can use this command:
# exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
#
# #for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
# exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps
#
# exec-once = rofi -show drun -no-lazy-grab

# 2. The GTK stuff (Keep this! It fixes apps like Firefox/Obsidian)
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" exec-once = xdg-desktop-portal-kde

# Set GTK theme to a dark variant
exec = gsettings set org.gnome.desktop.interface gtk-theme "Breeze-Dark"

# Set the dark mode preference (for GTK4/Libadwaita)
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# Optional: Set the icon theme so Thunar doesn't look like 1995
exec = gsettings set org.gnome.desktop.interface icon-theme "breeze-dark"
