
# Set programs that you use
# $terminal = alacritty
$terminal = kitty
$fileManager = dolphin
$fileManager = thunar 
$browser = firefox
$firefox = firefox
$chromium = chromium
$brave = brave
# $menu = rofi -config ~/.config/rofi/app-launcher.rasi -show drun
$menu = ~/.config/rofi/launchers/type-3/launcher.sh
# $menu = rofi -show drun
# $menu = $HOME/.config/rofi/power-menu.rasi
$wiman = tmux

