# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
# windowrulev2 = suppressevent maximize, class:.*
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
# windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# windowrulev2 = float, class:^(nm-connection-editor)$
windowrule {
  name = windowrule-3
  float = on
  match:class = ^(nm-connection-editor)$
}

windowrule {
  name = windowrule-4
  float = 1
  # center = 1
  # size = 300 400
  match:class = ^(galculator)$
}

# windowrulev2 = float, initialClas: thunar, title: Rename: .*
windowrule {
  name = windowrule-5
  float = on
  match:class = ^(thunar)$
  match:title = ^(Rename.*)$
}
