[opener]
image = [{ run = "gwenview \"$@\"", desc = "Gwenview" }]

image-term = [{ run = "feh --auto-zoom --scale-down \"$@\"", desc = "Feh"}]

video = [{ run = "mpv \"$@\"", desc = "Mpv" }]

# audio = [{ run = "open --use=play_audio", desc = "Play audio in background with mpv" }]
# audio = [{ run = "vlc \"$@\"", desc = "VLC" }]

pdf = [{ run = "okular \"$@\"", desc = "Okular" }]

text = [{ run = "nvim \"$@\"", desc = "Neovim", block = true }]

browser = [{ run = "firefox \"$@\"", desc = "Firefox" }]

zip = [{ run = "ark \"$@\"", desc = "Ark" }]

play_audio = [{ run = 'mpv --audio-display=no --video=no "$@"', orphan = true, for = "unix" }]

[open]
rules = [
  # { mime = "image/*", use = "image" },
  { mime = "image/*", use = "image-term" },
  { mime = "video/*", use = "video" },
  { mime = "audio/*", use = "play_audio" },
  # { mime = "audio/*", use = "audio" },
  { mime = "application/pdf", use = "pdf" },
  { mime = "text/*", use = "text" },
  { mime = "application/zip", use = "zip" },
]

# [manager]
# prepend_keymap = [
#   { on = [ "<C-Enter>", ], run = "open --opener=browser", desc = "Open in Firefox" },
#   { on = [ "p" ], run = "open --use=play_audio", desc = "Play audio in background with mpv"},
# ]

# [[manager.prepend_keymap]]
# on   = [ "p" ]
# run  = "open --use=play_audio"
# desc = "Play audio in background with mpv"
