

music_directory		"/home/ameen/Music"
playlist_directory		"/home/ameen/.mpd/playlists"
db_file			"/home/ameen/.mpd/database"

log_file			"/home/ameen/.mpd/log"


state_file			"/home/ameen/.mpd/state"


auto_update	"yes"


follow_outside_symlinks	"yes"
follow_inside_symlinks		"yes"







input {
        plugin "curl"
}


audio_output {
	type		"pulse"
	name		"My Pulse Output"
}

 # audio_output {
 #    type   "fifo"
 #    name   "my_fifo"
 #    path   "/tmp/mpd.fifo"
 #    format "44100:16:2"
 # }




