# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$
# windowrule = match:class kitty, persistent_size 1

windowrule = match:class .*, persistent_size 1
# windowrule = match:class thunar, persistent_size 1

# Ignore maximize requests from apps. You'll probably like this.
# windowrulev2 = suppressevent maximize, class:.*

windowrule =  match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
# windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# windowrulev2 = float, class:^(nm-connection-editor)$
windowrule = match:class ^(nm-connection-editor)$, float 1


windowrule = match:class org.gnome.Calculator, float 1
windowrule = match:class org.gnome.Cheese, float 1, size 505 625

# windowrulev2 = float, initialClas: thunar, title: Rename: .*
# windowrule = match:class ^(thunar)$, match:title ^(Rename.*)$, float 1
windowrule = match:class ^(thunar)$, match:title .*Rename.*, float 1


windowrule = match:class ^(thunar)$, match:title .*File Operation Progress.*, float 1

windowrule = match:class Tk, float 1

windowrule = match:class mpv, float 1

windowrule = match:class firefox, match:title Picture-in-Picture, float 1

windowrule = match:title ^(Open File)$, float 1

windowrule = match:class xdg-desktop-portal-gtk, float 1

# windowrule = match:initialClass org.godotengine.ProjectManager, match:title .*Project Manager.*, float 1
windowrule = match:initial_class org.godotengine.ProjectManager, match:initial_title Godot, float 1
windowrule = match:initial_class org.godotengine.ProjectManager, match:initial_title Godot, size 864 600
# windowrule = match:class ^(Godot)$, match:title ^(Project Manager.*)$, float 1

windowrule = match:class brave-browser, match:title .*Sign in.*, float 1

# windowrule = match:initial_title Godot, match:title ^(DEBUG.*)$, float 1
# windowrule = match:title ^.*(DEBUG).*$, float 1
windowrule = match:initial_title Godot, float 1
windowrule = match:class org.godotengine.Editor, match:initial_title Godot, tile 1

windowrule = match:class org.kde.gwenview, float 1

windowrule = match:class orbiter.exe, match:title .*Orbiter Server Launchpad.*, float 1

windowrule = match:class org.kde.okular, float 1
windowrule = match:class org.freedesktop.impl.portal.desktop.kde, float 1
# windowrule {
# 	name = shimeji
# 	match:class = oneko
#
# 	float = true
# 	no_blur = true
# 	no_focus = true
# 	no_shadow = true
# 	border_size = 0
# }

##matuwall window rules
### Window Mode
windowrule = float true, match:class com\.kwimy\.Matuwall
windowrule = animation slide top, match:class com\.kwimy\.Matuwall
windowrule = rounding 15, match:class com\.kwimy\.Matuwall
windowrule = border_size 0, match:class com\.kwimy\.Matuwall
windowrule = rounding_power 2, match:class com\.kwimy\.Matuwall
windowrule = no_shadow on, match:class com\.kwimy\.Matuwall

### Panel Mode
layerrule = match:namespace matuwall, blur on
layerrule = match:namespace matuwall, ignore_alpha 0.5

### Backdrop
layerrule = match:namespace matuwall-backdrop, animation fade
# layerrule = match:namespace matuwall-backdrop, blur on
# layerrule = match:namespace matuwall-backdrop, ignore_alpha 0.2
